// Code generated by abstraction-idl from abstraction-model/model.thrift. DO NOT EDIT.

#include <abstraction/download/request/rec.h>
#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::model::api {

using Raw = std::string;

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};
using OAImported0 = ::abstraction::download::request::Request;
struct Reader;
inline void enc_oaimported0(std::string&, const OAImported0&, int);
inline OAImported0 decode_oaimported0(Reader&);

inline const std::vector<std::string> kLookupOutcomeNames = {"resolved", "invalid", "unavailable", "unsupported_mapping", "forbidden"};
inline const std::string kLookupOutcomeUnknown = "refuse";

inline const std::vector<std::string> kResolverOperations = {"Registry", "Resolve"};

inline const std::vector<std::string> kRegistryOperations = {"Add", "SetLocal", "Resolve"};

struct Ref {
    std::string registry;
    std::string repo;
    std::string revision;
    std::string quant;
    std::string file;
};

struct LookupResult {
    std::string outcome;
    std::optional<OAImported0> request;
};

struct OAModelResolverResolveArguments {
    Ref ref;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

struct OAServiceReply {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    bool ok = false;
    Raw payload;
};

struct OAServiceError {
    std::string code;
    std::string message;
};

struct OAModelResolverResolveResult {
    LookupResult value;
};

inline void enc_ref(std::string& out, const Ref& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "registry");
    out += ": ";
    esc(out, v.registry);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "repo");
    out += ": ";
    esc(out, v.repo);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "revision");
    out += ": ";
    esc(out, v.revision);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "quant");
    out += ": ";
    esc(out, v.quant);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "file");
    out += ": ";
    esc(out, v.file);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_lookupresult(std::string& out, const LookupResult& v, int depth) {
    if (v.outcome != "resolved" && v.outcome != "invalid" && v.outcome != "unavailable" && v.outcome != "unsupported_mapping" && v.outcome != "forbidden") { throw Refusal("bad_enum",0); }
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "outcome");
    out += ": ";
    esc(out, v.outcome);
    if (v.request.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "request");
        out += ": ";
        enc_oaimported0(out, *v.request, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oamodelresolverresolvearguments(std::string& out, const OAModelResolverResolveArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ref");
    out += ": ";
    enc_ref(out, v.ref, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceframe(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaservicereply(std::string& out, const OAServiceReply& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ok");
    out += ": ";
    out += v.ok ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "payload");
    out += ": ";
    out += v.payload;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceerror(std::string& out, const OAServiceError& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, v.code);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "message");
    out += ": ";
    esc(out, v.message);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oamodelresolverresolveresult(std::string& out, const OAModelResolverResolveResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_lookupresult(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;



inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;
 int limit = kDepthLimit;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > limit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline Ref decode_ref(Reader& r);
inline LookupResult decode_lookupresult(Reader& r);
inline OAModelResolverResolveArguments decode_oamodelresolverresolvearguments(Reader& r);
inline OAServiceFrame decode_oaserviceframe(Reader& r);
inline OAServiceReply decode_oaservicereply(Reader& r);
inline OAServiceError decode_oaserviceerror(Reader& r);
inline OAModelResolverResolveResult decode_oamodelresolverresolveresult(Reader& r);

inline Ref decode_ref(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Ref v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "registry") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.registry = r.str();
            } else if (key == "repo") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.repo = r.str();
            } else if (key == "revision") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.revision = r.str();
            } else if (key == "quant") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.quant = r.str();
            } else if (key == "file") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.file = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline LookupResult decode_lookupresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    LookupResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "outcome") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.outcome = r.str();
            } else if (key == "request") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.request = decode_oaimported0(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    if (v.outcome != "resolved" && v.outcome != "invalid" && v.outcome != "unavailable" && v.outcome != "unsupported_mapping" && v.outcome != "forbidden") { r.refuse("bad_enum"); }
    return v;
}

inline OAModelResolverResolveArguments decode_oamodelresolverresolvearguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAModelResolverResolveArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "ref") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.ref = decode_ref(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oaserviceframe(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline OAServiceReply decode_oaservicereply(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceReply v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "ok") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.ok = r.boolean();
            } else if (key == "payload") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.payload = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline OAServiceError decode_oaserviceerror(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceError v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "code") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.code = r.str();
            } else if (key == "message") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.message = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OAModelResolverResolveResult decode_oamodelresolverresolveresult(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAModelResolverResolveResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_lookupresult(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline Ref decode(std::string_view data) {
    Reader r{data};
    r.skip_ws();
    Ref v = decode_ref(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}

struct FrameWriter{virtual ~FrameWriter()=default;virtual void WriteFrame(std::string_view)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oaserviceframe(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}

struct FrameExchanger{virtual ~FrameExchanger()=default;virtual std::string ExchangeFrame(std::string_view)=0;};
struct ServiceError:std::runtime_error{std::string code,message;ServiceError(std::string c,std::string m):std::runtime_error(m.empty()?c:m),code(c),message(m){}};
inline Raw service_response(std::string_view frame,std::string_view service,std::string_view method){
 Reader r{frame};r.skip_ws();auto v=decode_oaservicereply(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");if(v.service!=service||v.method!=method)throw DispatchError("mismatched_response");
 if(!v.ok){Reader e{v.payload};e.depth=1;e.skip_ws();auto error=decode_oaserviceerror(e);e.skip_ws();if(e.pos!=e.buf.size())e.refuse("trailing_bytes");if(error.code.empty())throw DispatchError("invalid_error");throw ServiceError(error.code,error.message);}return v.payload;
}
inline std::string service_reply(const OAServiceFrame& request,const Raw& payload,const ServiceError* error=nullptr){
 OAServiceReply reply;reply.version=1;reply.service=request.service;reply.method=request.method;reply.ok=error==nullptr;reply.payload=payload;
 if(error){OAServiceError e;e.code=error->code.empty()?"handler_error":error->code;e.message=error->message;reply.payload.clear();enc_oaserviceerror(reply.payload,e,1);}
 std::string frame;enc_oaservicereply(frame,reply,0);Reader r{frame};r.skip_ws();decode_oaservicereply(r);return frame;
}
struct ModelResolver{virtual ~ModelResolver()=default;
virtual LookupResult Resolve(const Ref& arg0)=0;
};
template<class Transport>struct ModelResolverClient:ModelResolver{Transport& transport_;explicit ModelResolverClient(Transport&t):transport_(t){}
LookupResult Resolve(const Ref& arg0)override{OAModelResolverResolveArguments args;
args.ref=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.model/resolver@1";v.method="Resolve";enc_oamodelresolverresolvearguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
auto response=transport_.ExchangeFrame(frame);auto payload=service_response(response,v.service,v.method);Reader r{payload};r.depth=1;r.skip_ws();auto result=decode_oamodelresolverresolveresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct ModelResolverService{inline static constexpr std::string_view wire_name="abstraction.model/resolver@1";inline static constexpr std::string_view capability="abstraction.model";template<class Transport>using Client=ModelResolverClient<Transport>;};
struct ModelResolverDispatcher:FrameWriter,FrameExchanger{ModelResolver&handler;explicit ModelResolverDispatcher(ModelResolver&h):handler(h){}
void WriteFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.model/resolver@1")throw DispatchError("unknown_service");
if(v.method=="Resolve"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string ExchangeFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.model/resolver@1"){ServiceError e("unknown_service","");return service_reply(v,"",&e);}
try{
if(v.method=="Resolve"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oamodelresolverresolvearguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_Resolve(args);return service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return service_reply(v,"",&error);}
}
Raw invoke_Resolve(const OAModelResolverResolveArguments&args){
LookupResult result{};
try{
result=handler.Resolve(args.ref);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
OAModelResolverResolveResult value;
value.value=result;
Raw payload;enc_oamodelresolverresolveresult(payload,value,1);Reader r{payload};r.depth=1;r.skip_ws();decode_oamodelresolverresolveresult(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
};

inline void enc_oaimported0(std::string& out,const OAImported0& v,int depth){try{out += ::abstraction::download::request::encode_request_at(v,depth);}catch(const ::abstraction::download::request::Refusal& e){throw Refusal(e.word,e.offset);}}
inline OAImported0 decode_oaimported0(Reader& r){try{std::size_t n=0;auto v=::abstraction::download::request::decode_request_at(r.buf.substr(r.pos),r.depth,r.limit,n);r.pos+=n;return v;}catch(const ::abstraction::download::request::Refusal& e){throw Refusal(e.word,r.pos+e.offset);}}

inline Ref decode_ref_at(std::string_view in,int depth,int limit,std::size_t& consumed){Reader r{in};if(depth<0||limit<1)r.refuse("depth_exceeded");r.depth=depth;r.limit=limit<kDepthLimit?limit:kDepthLimit;r.skip_ws();auto v=decode_ref(r);consumed=r.pos;return v;}
inline std::string encode_ref_at(const Ref& v,int depth){Reader r{""};if(depth<0||depth>=kDepthLimit)r.refuse("depth_exceeded");std::string out;enc_ref(out,v,depth);std::size_t n=0;decode_ref_at(out,depth,kDepthLimit,n);return out;}
inline std::string encode_ref(const Ref& v){return encode_ref_at(v,0)+"\n";}
inline Ref decode_ref(std::string_view in){std::size_t n=0;auto v=decode_ref_at(in,0,kDepthLimit,n);Reader r{in};r.pos=n;r.skip_ws();if(r.pos!=in.size())r.refuse("trailing_bytes");return v;}

inline LookupResult decode_lookupresult_at(std::string_view in,int depth,int limit,std::size_t& consumed){Reader r{in};if(depth<0||limit<1)r.refuse("depth_exceeded");r.depth=depth;r.limit=limit<kDepthLimit?limit:kDepthLimit;r.skip_ws();auto v=decode_lookupresult(r);consumed=r.pos;return v;}
inline std::string encode_lookupresult_at(const LookupResult& v,int depth){Reader r{""};if(depth<0||depth>=kDepthLimit)r.refuse("depth_exceeded");std::string out;enc_lookupresult(out,v,depth);std::size_t n=0;decode_lookupresult_at(out,depth,kDepthLimit,n);return out;}
inline std::string encode_lookupresult(const LookupResult& v){return encode_lookupresult_at(v,0)+"\n";}
inline LookupResult decode_lookupresult(std::string_view in){std::size_t n=0;auto v=decode_lookupresult_at(in,0,kDepthLimit,n);Reader r{in};r.pos=n;r.skip_ws();if(r.pos!=in.size())r.refuse("trailing_bytes");return v;}

inline std::string encode(const Ref& v){return encode_ref(v);}

}  // namespace abstraction::model::api
